name: Writerside docs errors parser
description: Parse report.json test results report
branding:
  icon: corner-down-right
  color: purple

inputs:
  instance:
    description: 'The instance variable'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'artifacts/report.json'
    - '${{ env.INSTANCE }}'