name: Writerside docs errors parser
description: Parse report.json test results report
branding:
  icon: corner-down-right
  color: purple

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'artifacts/report.json'
    - '${{ env.INSTANCE }}'